services:  
  db:
    image: postgres:17.4-alpine
    container_name: Postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    # DB起動完了までappコンテナの起動を待つための設定
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=${DATABASE_USER} --dbname=${DATABASE_NAME}"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s
    # 既存プロジェクトとのポート競合を避けるためにポートフォワード
    ports:
      - "${DATABASE_PORT}:5432"
    # DBの削除を容易にするためにプロジェクト内のディレクトリにデータを保存
    volumes:
      - ./backend/docker/postgresql/data:/var/lib/postgresql/data
    networks:
      - fastapi_network

  app:
    container_name: FastAPI_app
    build:
      context: .
      dockerfile: ./backend/docker/fastapi/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT}:8000"
    expose:
      - "${API_PORT}"
    volumes:
      - ./backend:/workdir
    networks:
      - fastapi_network

networks:
  fastapi_network:
    name: fastapi_network
    driver: bridge

volumes:
  postgres_data:
