services:
  nextjs:
    container_name: NextJS_admin
    build:
      context: .
      dockerfile: ./frontend/docker/nextjs/Dockerfile
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend/admin:/workdir
      - /workdir/node_modules
      - /workdir/.next
    networks:
      - fastapi_network

networks:
  fastapi_network:
    name: fastapi_network
    driver: bridge
