services:
  db:
    image: postgres:17.4-alpine
    container_name: test_db
    restart: always
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    # DB起動完了までappコンテナの起動を待つための設定
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=${DATABASE_USER} --dbname=${DATABASE_NAME}"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s
    # 既存プロジェクトとのポート競合を避けるためにポートフォワード
    ports:
      - "${DATABASE_PORT}:5432"
    # DBの削除を容易にするためにプロジェクト内のディレクトリにデータを保存
    volumes:
      - ./backend/docker/postgresql/data:/var/lib/postgresql/test_data
    networks:
      - fastapi_network
    # リソース制限を追加
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M