version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/dockerfile
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL:DATABASE_URL: postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    expose:
      - "${API_PORT}"