services:
  nextjs:
    container_name: NextJS_app
    build:
      context: ./frontend
      dockerfile: ./docker/nextjs/Dockerfile
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - fastapi_network

networks:
  fastapi_network:
    name: fastapi_network
    driver: bridge
