"""is_admin Optional[bool]

Revision ID: 2bf0e3baa8d5
Revises: d792ea2958f9
Create Date: 2025-03-07 09:09:03.450776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf0e3baa8d5'
down_revision: Union[str, None] = 'd792ea2958f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
