"""change employee_id

Revision ID: 511483c944a1
Revises: 
Create Date: 2025-04-01 02:04:16.127273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511483c944a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.drop_column('users', 'emproyee_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emproyee_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
