"""add sweetname

Revision ID: e1d7f38958df
Revises: f4f1fb705483
Create Date: 2025-03-23 00:12:16.173819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d7f38958df'
down_revision: Union[str, None] = 'f4f1fb705483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sweetname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sweetname')
    # ### end Alembic commands ###
