"""add_ctstagename

Revision ID: f4f1fb705483
Revises: 3f3f7a2b19b4
Create Date: 2025-03-23 00:01:38.646698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f1fb705483'
down_revision: Union[str, None] = '3f3f7a2b19b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ctstagename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ctstagename')
    # ### end Alembic commands ###
